/** チャンネル由来データ。子表を親より先に消す順で、両方の削除処理から参照する。 */
export const CHANNEL_DATA_TABLES = [
  "analytics_raw_rows",
  "analytics_raw_reports",
  "caption_attempts",
  "caption_records",
  "reporting_orphan_objects",
  "reporting_authorizations",
  "reporting_reach_stage",
  "reporting_raw_reports",
  "reporting_jobs",
  "collection_series_status",
  "video_angles",
  "videos",
  "daily_metrics",
  "video_metrics",
  "video_reach_daily",
  "video_daily_metrics",
  "channel_daily_metrics",
  "comment_emotions",
  "psych_findings",
  "report_archives",
  "reports",
  "findings",
  "actions",
  "media_assets",
  "transcripts",
  "analysis_requests",
  "business_funnel_weekly",
  "funnel_targets",
  "studio_csv_columns",
  "studio_csv_unresolved_rows",
  "video_period_metrics",
  "studio_csv_imports",
] as const;
